# Generated by Django 5.1.1 on 2024-09-09 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 28, 1, 686747)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
