# Generated by Django 5.1.1 on 2024-09-09 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_alter_customuser_date_joined_alter_movie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 45, 31, 45387)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=255, unique=True),
        ),
    ]
