# Generated by Django 5.1.1 on 2024-09-09 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_alter_customuser_date_joined_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 19, 34, 34, 901522)),
        ),
    ]
