# Generated by Django 5.1.1 on 2024-09-10 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0005_movie_post_user_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 15, 11, 29, 615632)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(default='', upload_to='media/videos'),
        ),
    ]
