# Generated by Django 5.1.1 on 2024-09-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0007_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 22, 38, 9, 315729)),
        ),
    ]
