# Generated by Django 5.1.1 on 2024-09-10 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0008_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 2, 6, 8, 455072)),
        ),
    ]
