# Generated by Django 5.1.1 on 2024-09-11 06:48

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0014_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 48, 55, 234819)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='media/videos'), upload_to='media/videos'),
        ),
    ]
