# Generated by Django 5.1.1 on 2024-09-11 06:59

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0015_alter_customuser_date_joined_alter_movie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 59, 15, 95855)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/videos'), upload_to='videos/'),
        ),
    ]
