# Generated by Django 5.1.1 on 2024-09-11 13:39

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0017_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='originally_movie',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='media/videos'), upload_to='originally/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 22, 39, 56, 426805)),
        ),
    ]
