# Generated by Django 5.1.1 on 2024-09-13 04:38

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0019_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 13, 38, 23, 876552)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/media/videos'), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='originally_movie',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='media/media/videos'), upload_to='originally/'),
        ),
    ]
