# Generated by Django 5.1.1 on 2024-09-13 05:31

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0020_alter_customuser_date_joined_alter_movie_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 31, 24, 22909)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='videos'), upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='originally_movie',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='videos'), upload_to='originally/'),
        ),
    ]
