# Generated by Django 5.1.1 on 2024-09-13 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0021_alter_customuser_date_joined_alter_movie_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 5, 46, 734346)),
        ),
    ]
