# Generated by Django 5.1.1 on 2024-09-13 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0022_movie_public_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rio_recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 16, 10, 50, 577276)),
        ),
    ]
