# Generated by Django 5.1.1 on 2024-09-16 09:15

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0023_movie_rio_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(location='videos'), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 18, 15, 43, 971195)),
        ),
    ]
