# Generated by Django 5.1.1 on 2024-10-08 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0035_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 0, 20, 22, 407275)),
        ),
    ]
