# Generated by Django 4.2 on 2024-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0037_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
